# Change these first
owner: smbcat16 # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository

sites:
  - name: moodle
    url: https://adf-elearning.org
  - name: overleaf
    url: https://overleaf.adf-elearning.org
  - name: code
    url: https://code.adf-elearning.org
    icon: https://upload.wikimedia.org/wikipedia/commons/9/9a/Visual_Studio_Code_1.35_icon.svg
  - name: pdf
    url: https://pdf.adf-elearning.org
  - name: gemini
    url: https://gemini.adf.cc.ua
    icon: https://uxwing.com/wp-content/themes/uxwing/download/brands-and-social-media/google-gemini-icon.svg
  - name: Google DNS 8.8.8.8
    check: "tcp-ping"
    url: 8.8.8.8
    port: 53
    icon: https://icons.veryicon.com/png/o/application/app-general-icon-01/dns-1.png


status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: up.adf.cc.ua
  # baseUrl: /your-repo-name
  logoUrl: https://uptime.com/images/brand/svgs/LightMode/icon.svg
  name: ADF-UP
  introTitle: "**UPTIME** monitors ADF websites and servers!"
  introMessage: The monitoring **real-time** data.
  favicon: https://raw.githubusercontent.com/smbcat16/uptime/master/assets/upptime-icon.svg
  theme: night
  # Available themes are light, dark, night or ocean.
#  navbar:
#    - title: Status Page
#      href: /
#    - title: GitHub
#      href: https://github.com/$OWNER/$REPO
#    - title: ADF
#      href: https://adf-elearning.org
#    - title: Overleaf
#      href: https://overleaf.adf-elearning.org

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration

i18n:
  footer: This page is hosted on [GitHub]($REPO) project since @2024-08-13.
  
workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"
